#Heart Attack Prediction

####Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

####Loading Dataset

In [2]:
df = pd.read_csv("/content/HeartAttack (1).csv")

In [3]:
df.head(10)

age  sex  cp trestbps chol fbs restecg thalach exang  oldpeak slope ca  \
0   28    1   2      130  132   0       2     185     0      0.0     ?  ?   
1   29    1   2      120  243   0       0     160     0      0.0     ?  ?   
2   29    1   2      140    ?   0       0     170     0      0.0     ?  ?   
3   30    0   1      170  237   0       1     170     0      0.0     ?  ?   
4   31    0   2      100  219   0       1     150     0      0.0     ?  ?   
5   32    0   2      105  198   0       0     165     0      0.0     ?  ?   
6   32    1   2      110  225   0       0     184     0      0.0     ?  ?   
7   32    1   2      125  254   0       0     155     0      0.0     ?  ?   
8   33    1   3      120  298   0       0     185     0      0.0     ?  ?   
9   34    0   2      130  161   0       0     190     0      0.0     ?  ?   

  thal  num         
0    ?           0  
1    ?           0  
2    ?           0  
3    6           0  
4    ?           0  
5    ?           0  
6    ?           0  
7    ?           0  
8    ?           0  
9    ?           0

In [4]:
df.tail(5)

age  sex  cp trestbps chol fbs restecg thalach exang  oldpeak slope ca  \
289   52    1   4      160  331   0       0      94     1      2.5     ?  ?   
290   54    0   3      130  294   0       1     100     1      0.0     2  ?   
291   56    1   4      155  342   1       0     150     1      3.0     2  ?   
292   58    0   2      180  393   0       0     110     1      1.0     2  ?   
293   65    1   4      130  275   0       1     115     1      1.0     2  ?   

    thal  num         
289    ?           1  
290    ?           1  
291    ?           1  
292    7           1  
293    ?           1

####Data information and Cleaning

In [8]:
df = pd.read_csv("/content/HeartAttack (1).csv",na_values='?')

In [9]:
df.head(10)

age  sex  cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0   28    1   2     130.0  132.0  0.0      2.0    185.0    0.0      0.0   
1   29    1   2     120.0  243.0  0.0      0.0    160.0    0.0      0.0   
2   29    1   2     140.0    NaN  0.0      0.0    170.0    0.0      0.0   
3   30    0   1     170.0  237.0  0.0      1.0    170.0    0.0      0.0   
4   31    0   2     100.0  219.0  0.0      1.0    150.0    0.0      0.0   
5   32    0   2     105.0  198.0  0.0      0.0    165.0    0.0      0.0   
6   32    1   2     110.0  225.0  0.0      0.0    184.0    0.0      0.0   
7   32    1   2     125.0  254.0  0.0      0.0    155.0    0.0      0.0   
8   33    1   3     120.0  298.0  0.0      0.0    185.0    0.0      0.0   
9   34    0   2     130.0  161.0  0.0      0.0    190.0    0.0      0.0   

   slope  ca  thal  num         
0    NaN NaN   NaN           0  
1    NaN NaN   NaN           0  
2    NaN NaN   NaN           0  
3    NaN NaN   6.0           0  
4    NaN NaN   NaN           0  
5    NaN NaN   NaN           0  
6    NaN NaN   NaN           0  
7    NaN NaN   NaN           0  
8    NaN NaN   NaN           0  
9    NaN NaN   NaN           0

In [10]:
df.tail(5)

age  sex  cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
289   52    1   4     160.0  331.0  0.0      0.0     94.0    1.0      2.5   
290   54    0   3     130.0  294.0  0.0      1.0    100.0    1.0      0.0   
291   56    1   4     155.0  342.0  1.0      0.0    150.0    1.0      3.0   
292   58    0   2     180.0  393.0  0.0      0.0    110.0    1.0      1.0   
293   65    1   4     130.0  275.0  0.0      1.0    115.0    1.0      1.0   

     slope  ca  thal  num         
289    NaN NaN   NaN           1  
290    2.0 NaN   NaN           1  
291    2.0 NaN   NaN           1  
292    2.0 NaN   7.0           1  
293    2.0 NaN   NaN           1

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294 entries, 0 to 293
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   age         294 non-null    int64  
 1   sex         294 non-null    int64  
 2   cp          294 non-null    int64  
 3   trestbps    293 non-null    float64
 4   chol        271 non-null    float64
 5   fbs         286 non-null    float64
 6   restecg     293 non-null    float64
 7   thalach     293 non-null    float64
 8   exang       293 non-null    float64
 9   oldpeak     294 non-null    float64
 10  slope       104 non-null    float64
 11  ca          3 non-null      float64
 12  thal        28 non-null     float64
 13  num         294 non-null    int64  
dtypes: float64(10), int64(4)
memory usage: 32.3 KB


In [12]:
df.isnull().sum()

age             0
sex             0
cp              0
trestbps        1
chol           23
fbs             8
restecg         1
thalach         1
exang           1
oldpeak         0
slope         190
ca            291
thal          266
num             0
dtype: int64

In [13]:
df.describe()

age         sex          cp    trestbps        chol         fbs  \
count  294.000000  294.000000  294.000000  293.000000  271.000000  286.000000   
mean    47.826531    0.724490    2.982993  132.583618  250.848708    0.069930   
std      7.811812    0.447533    0.965117   17.626568   67.657711    0.255476   
min     28.000000    0.000000    1.000000   92.000000   85.000000    0.000000   
25%     42.000000    0.000000    2.000000  120.000000  209.000000    0.000000   
50%     49.000000    1.000000    3.000000  130.000000  243.000000    0.000000   
75%     54.000000    1.000000    4.000000  140.000000  282.500000    0.000000   
max     66.000000    1.000000    4.000000  200.000000  603.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope   ca  \
count  293.000000  293.000000  293.000000  294.000000  104.000000  3.0   
mean     0.218430  139.129693    0.303754    0.586054    1.894231  0.0   
std      0.460868   23.589749    0.460665    0.908648    0.338995  0.0   
min      0.000000   82.000000    0.000000    0.000000    1.000000  0.0   
25%      0.000000  122.000000    0.000000    0.000000    2.000000  0.0   
50%      0.000000  140.000000    0.000000    0.000000    2.000000  0.0   
75%      0.000000  155.000000    1.000000    1.000000    2.000000  0.0   
max      2.000000  190.000000    1.000000    5.000000    3.000000  0.0   

            thal  num         
count  28.000000  294.000000  
mean    5.642857    0.360544  
std     1.615074    0.480977  
min     3.000000    0.000000  
25%     5.250000    0.000000  
50%     6.000000    0.000000  
75%     7.000000    1.000000  
max     7.000000    1.000000

######Removing Null Values

In [14]:
### removing columns containing null values
df = df.drop(columns = ["slope","ca","thal"],axis = 1)

In [15]:
df.head()

age  sex  cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0   28    1   2     130.0  132.0  0.0      2.0    185.0    0.0      0.0   
1   29    1   2     120.0  243.0  0.0      0.0    160.0    0.0      0.0   
2   29    1   2     140.0    NaN  0.0      0.0    170.0    0.0      0.0   
3   30    0   1     170.0  237.0  0.0      1.0    170.0    0.0      0.0   
4   31    0   2     100.0  219.0  0.0      1.0    150.0    0.0      0.0   

   num         
0           0  
1           0  
2           0  
3           0  
4           0

In [16]:
### removing rows containing null values
df = df.dropna()

In [17]:
df.head()

age  sex  cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0   28    1   2     130.0  132.0  0.0      2.0    185.0    0.0      0.0   
1   29    1   2     120.0  243.0  0.0      0.0    160.0    0.0      0.0   
3   30    0   1     170.0  237.0  0.0      1.0    170.0    0.0      0.0   
4   31    0   2     100.0  219.0  0.0      1.0    150.0    0.0      0.0   
5   32    0   2     105.0  198.0  0.0      0.0    165.0    0.0      0.0   

   num         
0           0  
1           0  
3           0  
4           0  
5           0

In [19]:
#checking data after cleaning
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 261 entries, 0 to 293
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   age         261 non-null    int64  
 1   sex         261 non-null    int64  
 2   cp          261 non-null    int64  
 3   trestbps    261 non-null    float64
 4   chol        261 non-null    float64
 5   fbs         261 non-null    float64
 6   restecg     261 non-null    float64
 7   thalach     261 non-null    float64
 8   exang       261 non-null    float64
 9   oldpeak     261 non-null    float64
 10  num         261 non-null    int64  
dtypes: float64(7), int64(4)
memory usage: 24.5 KB


In [20]:
df.isnull().sum()

age           0
sex           0
cp            0
trestbps      0
chol          0
fbs           0
restecg       0
thalach       0
exang         0
oldpeak       0
num           0
dtype: int64

In [21]:
df["sex"].value_counts()

1    192
0     69
Name: sex, dtype: int64

In [22]:
df["cp"].value_counts()

4    113
2     92
3     46
1     10
Name: cp, dtype: int64

In [23]:
df["restecg"].value_counts()

0.0    208
1.0     47
2.0      6
Name: restecg, dtype: int64

####Creating Dummies To Convert Categorical data to One Hot Encoding

In [24]:
df = pd.get_dummies(df,columns = ["cp","restecg"])

In [25]:
df.head()

age  sex  trestbps   chol  fbs  thalach  exang  oldpeak  num         cp_1  \
0   28    1     130.0  132.0  0.0    185.0    0.0      0.0           0     0   
1   29    1     120.0  243.0  0.0    160.0    0.0      0.0           0     0   
3   30    0     170.0  237.0  0.0    170.0    0.0      0.0           0     1   
4   31    0     100.0  219.0  0.0    150.0    0.0      0.0           0     0   
5   32    0     105.0  198.0  0.0    165.0    0.0      0.0           0     0   

   cp_2  cp_3  cp_4  restecg_0.0  restecg_1.0  restecg_2.0  
0     1     0     0            0            0            1  
1     1     0     0            1            0            0  
3     0     0     0            0            1            0  
4     1     0     0            0            1            0  
5     1     0     0            1            0            0

In [40]:
df.columns

Index(['age', 'sex', 'trestbps', 'chol', 'fbs', 'thalach', 'exang', 'oldpeak',
       'num       ', 'cp_1', 'cp_2', 'cp_3', 'cp_4', 'restecg_0.0',
       'restecg_1.0', 'restecg_2.0'],
      dtype='object')

In [41]:
#classifying num as target variable to separate it
df = df.rename(columns = {"num       ":"target"})

In [42]:
#labelling numerical and categorical columns

numerical_cols = ["age","trestbps","chol","thalach","oldpeak"]
cat_cols = list(set(df.columns) - set(numerical_cols) - {"target"})

In [43]:
df.head()

age  sex  trestbps   chol  fbs  thalach  exang  oldpeak  target  cp_1  \
0   28    1     130.0  132.0  0.0    185.0    0.0      0.0       0     0   
1   29    1     120.0  243.0  0.0    160.0    0.0      0.0       0     0   
3   30    0     170.0  237.0  0.0    170.0    0.0      0.0       0     1   
4   31    0     100.0  219.0  0.0    150.0    0.0      0.0       0     0   
5   32    0     105.0  198.0  0.0    165.0    0.0      0.0       0     0   

   cp_2  cp_3  cp_4  restecg_0.0  restecg_1.0  restecg_2.0  
0     1     0     0            0            0            1  
1     1     0     0            1            0            0  
3     0     0     0            0            1            0  
4     1     0     0            0            1            0  
5     1     0     0            1            0            0

In [44]:
cat_cols

['cp_3',
 'cp_4',
 'restecg_1.0',
 'sex',
 'exang',
 'restecg_0.0',
 'cp_1',
 'cp_2',
 'fbs',
 'restecg_2.0']

In [45]:
numerical_cols

['age', 'trestbps', 'chol', 'thalach', 'oldpeak']

#### Splitting Data

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
df_train , df_test = train_test_split(df,test_size = 0.2 , random_state = 42)

In [52]:
len(df_train) , len(df_test)

(208, 53)

##### Normalizing Data

In [55]:
from sklearn.preprocessing import StandardScaler

In [61]:
scaler = StandardScaler()
def get_features_and_target_arrays(df,numerical_cols,cat_cols,scaler):
  x_numeric_scaled = scaler.fit_transform(df[numerical_cols])
  x_categorical = df[cat_cols].to_numpy()
  x = np.hstack((x_categorical,x_numeric_scaled))
  y = df["target"]
  return x,y

In [62]:
x_train , y_train = get_features_and_target_arrays(df_train,cat_cols,numerical_cols,scaler)


#### Model using Logistic Regression

In [64]:
from sklearn.linear_model import LogisticRegression

In [65]:
model1 = LogisticRegression()
model1.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [66]:
x_test , y_test = get_features_and_target_arrays(df_test,cat_cols,numerical_cols,scaler)


In [67]:
y_pred1 = model1.predict(x_test)

In [73]:
# calculating error and accuracy of model
from sklearn.metrics import mean_squared_error,accuracy_score,confusion_matrix
mean_squared_error(y_test,y_pred1)


0.16981132075471697

In [74]:
accuracy_score(y_test,y_pred1)

0.8301886792452831

In [75]:
confusion_matrix(y_test,y_pred1)

array([[28,  5],
       [ 4, 16]])

#### Model Using Decision Tree

In [76]:
from sklearn.tree import DecisionTreeClassifier
model2 = DecisionTreeClassifier()

In [77]:
model2.fit(x_train,y_train)

DecisionTreeClassifier()

In [79]:
y_pred2 = model2.predict(x_test)

In [80]:
mean_squared_error(y_test,y_pred2)

0.3584905660377358

In [81]:
accuracy_score(y_test,y_pred2)

0.6415094339622641

In [82]:
confusion_matrix(y_test,y_pred2)

array([[23, 10],
       [ 9, 11]])

####Model Using RandomForest

In [83]:
from sklearn.ensemble import RandomForestClassifier
model3 = RandomForestClassifier()

In [84]:
model3.fit(x_train,y_train)

RandomForestClassifier()

In [85]:
y_pred3 = model3.predict(x_test)

In [86]:
mean_squared_error(y_test,y_pred3)

0.22641509433962265

In [87]:
accuracy_score(y_test,y_pred3)

0.7735849056603774

In [88]:
confusion_matrix(y_test,y_pred3)

array([[26,  7],
       [ 5, 15]])

#### Model Using Support Vector Machine

In [89]:
from sklearn.svm import SVC
model4 = SVC()

In [91]:
model4.fit(x_train,y_train)

SVC()

In [92]:
y_pred4 = model4.predict(x_test)

In [93]:
mean_squared_error(y_test,y_pred4)

0.33962264150943394

In [94]:
accuracy_score(y_test,y_pred4)

0.660377358490566

In [95]:
confusion_matrix(y_test,y_pred4)

array([[33,  0],
       [18,  2]])